#!/bin/sh

prompt () {
    if [ $? == 0 ]; then
        echo
        echo "Stage success. Proceed to $1 stage? y/n"
        read $2
        if [ $2 == "n" ]; then
            echo "Aborting."
            exit
        fi
    else
        echo
        echo "Stage failure. Aborting."
        exit
    fi
}

if [ "$1" == "build" ]; then
    ./buildtool clean
    autoreconf -i
    ./configure
    make
elif [ "$1" == "clean" ]; then
    git clean -dfx
elif [ "$1" == "slowbuild" ]; then
    echo "Cleaning..."
    ./buildtool clean
    prompt "autoconfiguration"
    autoreconf -i
    prompt "configuration"
    ./configure
    prompt "build"
    make
    if [ $? == 0 ]; then
        echo
        echo "Build successful."
    else
        echo
        echo "Build failed."
    fi
else
    echo "Options:"
    echo
    echo "build - rebuild and compile the project"
    echo "clean - remove all files untracked by git"
    echo "slowbuild - ask for confirmation after each stage of building"
fi
